CONFIG = {
    "model_name": "Qwen/Qwen2.5-0.5B-Instruct",
    "custom_tokenizer_path": "qwen_abkhaz_tokenizer",
    "max_lines_per_file": None,
    "data_dirs": ["./done"],
    "output_dir": "./qwen_finetuned",
    "max_length": 256,
    "batch_size": 8,
    "gradient_accumulation_steps": 2,
    "epochs": 5,
    "learning_rate": 3e-5,
    "lr_scheduler_type": "cosine",
    "warmup_ratio": 0.1,
    "weight_decay": 0.01,
    "save_steps": 2000,
    "logging_steps": 200,
    "seed": 42,
    "add_formatter_files_times": 50,
    "use_wandb": True,
    "eval_steps": 2000,
    "resume_from_checkpoint": True,
} 